name: FiGWiG
favicon: null
layout_spectrum: 0.19955
typography_spectrum: 0.04407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.43451174767687917
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.7373990344349295
purpose: []
